datasets:
  daisee:
    root_dir: "/mnt/c/Users/puneet/Downloads/DAiSEE"
    train_csv: "../train.csv"
    val_csv: "../val.csv"
    test_csv: "../test.csv"
    test_quick_csv: "../test_quick.csv"
    label_columns: [Engagement, Boredom, Confusion, Frustration]
    num_classes: 4
